FROM python:3.11-slim-bookworm
LABEL authors="vladimirsuponin"

WORKDIR /app

COPY ./data_generation_backend/ ./

RUN pip install --upgrade pip && \
    pip install "poetry>=2.0,<3.0" && \
    poetry config virtualenvs.create false && \
    poetry install

ENV PYTHONPATH /app/src:/app/config

CMD ["uvicorn", "src.main:app", "--workers", "4", "--host", "0.0.0.0", "--port", "8600"]

EXPOSE 8600
