FROM python:3.11-slim-bookworm
LABEL authors="vladimirsuponin"

WORKDIR /app

COPY ./data_generation_backend/ ./

RUN pip install --update pip && \
    pip install "poetry>=2.0,<3.0" && \
    poetry config virtualenvs.create false && \
    poetry install


ENTRYPOINT ["top", "-b"]